osx_image: xcode8
language: objective-c
podfile: Example/Podfile
before_install:
  - pod repo update
script: 
  - scan
after_success:
  - bundle exec slather
  - bash <(curl -s https://codecov.io/bash)
