osx_image: xcode8
language: objective-c
podfile: Example/Podfile
before_install:
  - pod repo update
before_script:
  - rvm head || true # https://github.com/travis-ci/travis-ci/issues/6307
script: 
  - scan
after_success:
  - bundle exec slather
  - bash <(curl -s https://codecov.io/bash)
